### ISSUE TITLE
In AlterTableStatement, format() always return null

### ISSUE THREAD

**Issue by beyondykk9** [sfa-siard/SqlParser#1]
In AlterTableStatement, the method format() always return null.

Why does only this method return null among the DdlStatement?

**Comment by HartwigThomas** [comment]
Possible reasons for your observation:
- You did not run build to generate the parser classes.
- The context you are trying to use was not implemented/tested because it was not essential for SIARD.
From the documentation:
"SqlParser is implemented as a separate project, because a quite general parser for SQL:2008 can be quite useful in its own right in other contexts than SIARD."
Thus SqlParser is a fragment which has been extensively tested for SIARD but which certainly must be improved by the community, which is interested in a general parser for SQL:2008.

Now I have examined the code and found, that format indeed returns null instead of sStatement. That is probably an editing error, which was never caught, because no tests were implemented. And no tests were implemented, because the function was not used by SIARD. I have changed the code for the next master version. But I do not have the resources to create extensive tests. These will have to be supplied by users who really need the function/class.

**Comment by beyondykk9** [comment]
I know that the code is not used by SIARD, but the code can be used by a JdbcBase extended code in case that it is needed.

I expect that the code will be modified soon.

Thanks.

**Comment by HartwigThomas** [comment]
Yes, it will be modified soon. Could you write tests for it?

**Comment by beyondykk9** [comment]
Yes, I have my own test code.

**Comment by HartwigThomas** [comment]
I shall check in a corrected master soon. It would be nice, if you were to share your tests.
